### ISSUE TITLE
Checkboxes and radios are too small in Firefox

### ISSUE THREAD

**Issue by faboweb** [fabric-design/components#106]
As show on the screenshot, checkbox and radio inputs are rendered in a tiny size in Firefox. They look fine in Chrome. Tested in FF 54 on mac.

https://wholesale-design-system.github.io/styleguide/#/atoms/forms

![image](https://user-images.githubusercontent.com/5869273/28619534-1577c0ee-7209-11e7-823c-3d0af82354fe.png)

**Comment by faboweb** [comment]
originally by @szafranek

**Comment by faboweb** [comment]
@fragsalat mentioned: Then just lets change [the styling for :after and :before] to the labels.

**Comment by fragsalat** [comment]
Done for switches but not for checkboxes and radio buttons right now

**Comment by fragsalat** [comment]
Done already
