### ISSUE TITLE
Filter panels wider than its parent element

### ISSUE THREAD

**Issue by myueksel** [fabric-design/components#109]
Very long content of filter panels are cuttet... sometimes more than necessary. Therefore it should be possible to customise panels width on given requirements, that panels could be wider than its parent element

Bad example how it should't look:
![screen shot 2017-07-28 at 16 41 48](https://user-images.githubusercontent.com/25901307/28722622-a8d34636-73b4-11e7-80fd-c3725b77c8e6.png)

**Comment by fokusferit** [comment]
Closing for now as a PR was merged.
