### ISSUE TITLE
Add Introduction Tutorials for every Framework

### ISSUE THREAD

**Issue by fokusferit** [fabric-design/components#31]
We should provide a (short) introduction in our Wiki for every framework where we use our components, e.g. Reactjs, Angular2, Aurelia etc.

**Comment by faboweb** [comment]
+1

**Comment by fokusferit** [comment]
@faboweb could you add your ng2 integration to https://github.com/wholesale-design-system/components/wiki/How-to-integrate-component-into-your-build-system ? Then we can close this one :)

**Comment by fragsalat** [comment]
It's on my todo list with low prio

**Comment by fragsalat** [comment]
It's done https://github.com/fabric-design/components/wiki/How-to-integrate-component-into-your-build-system
