### ISSUE TITLE
Arrow Icons in Week-Picker seem to be different in different browsers

### ISSUE THREAD

**Issue by faboweb** [fabric-design/components#34]
Tony:
![image](https://cloud.githubusercontent.com/assets/5869273/24359751/9206db9e-1305-11e7-947d-b1de38fc48d9.png)

Fabo:
![image](https://cloud.githubusercontent.com/assets/5869273/24359779/a287dcf2-1305-11e7-916e-cfa53d4bbef2.png)

Let's check back in some time of this is still an issue.

**Comment by szafranek** [comment]
Is this still a problem?

I tested the demo page in FF, Chrome and Safari (all on macOS, though) and the arrows look consistent.

Cc @fragsalat

**Comment by fragsalat** [comment]
I exchanged the arrow icons before some months with our icon font. So this is consistent now.
