### ISSUE TITLE
Date picker – calendar icon should be part of clickable area to invoke the popover

### ISSUE THREAD

**Issue by schluchter** [fabric-design/components#37]
![image](https://cloud.githubusercontent.com/assets/760158/24452240/90f6da14-1482-11e7-9b84-fb200e9d6fde.png)

Expected: In the date picker, the user can click anywhere inside the input field to invoke the popover.
Actual: In the date picker, the user cannot click on the calendar icon to invoke the popover.

**Comment by faboweb** [comment]
@fragsalat can you take of that?

**Comment by fokusferit** [comment]
@fragsalat did you fixed this one with #54 ? If yes could you close the issue :) ?

**Comment by fragsalat** [comment]
Nope. I'll fix this

**Comment by fragsalat** [comment]
It was fixed already but Jason found a even better solution by using pointer-events: none
