### ISSUE TITLE
Dropdown pop-over configurable with max-width

### ISSUE THREAD

**Issue by schluchter** [fabric-design/components#98]
#97 introduced a sensible default for sizing the pop-over used to pick values from the dropdown.

As a further enhancement to this component's API, I would suggest the following:

- Make the component configurable by the implementer to include a max-width
- When no max-width is supplied by the implementer, default to the behavior introduced in #97 
- When a max-width is supplied, set the dropdown to the max-width and truncate all values that are wider than the max-width
- If the content of the dropdown is narrower than the max-width, size it to accommodate the content and not wider.

Rationale: At design time, the average length of dropdown content is usually known. For usability purposes, minimizing the number of items that have to be truncated is optimal.

Problems/Questions: How to make this behavior responsive?

**Comment by fokusferit** [comment]
@fragsalat still open I guess ?

**Comment by fragsalat** [comment]
Ah sry it's closed already by #123
